#!/bin/sh
if [ -n "$1" ];then
	/sbin/wifi down
	case $1 in
		NONE )
			[ -n "$2" ] && uci set wireless.ap.ApCliSsid="$2"
			uci set wireless.ap.ApCliAuthMode='OPEN'
			uci set wireless.ap.ApCliEncrypType='NONE'
			uci delete wireless.ap.ApCliWPAPSK
			uci set wireless.ap.ApCliEnable='1'
			;;
		WPAPSK/AES )
			[ -n "$2" ] && uci set wireless.ap.ApCliSsid="$2"
			[ -n "$3" ] && uci set wireless.ap.ApCliWPAPSK="$3"
			uci set wireless.ap.ApCliAuthMode='WPAPSK'
			uci set wireless.ap.ApCliEncrypType='AES'
			uci set wireless.ap.ApCliEnable='1'
			;;
		WPAPSK/TKIPAES )
			[ -n "$2" ] && uci set wireless.ap.ApCliSsid="$2"
			[ -n "$3" ] && uci set wireless.ap.ApCliWPAPSK="$3"
			uci set wireless.ap.ApCliAuthMode='WPAPSK'
			uci set wireless.ap.ApCliEncrypType='AES'
			uci set wireless.ap.ApCliEnable='1'
			;;
		WPAPSK/TKIP )
			[ -n "$2" ] && uci set wireless.ap.ApCliSsid="$2"
			[ -n "$3" ] && uci set wireless.ap.ApCliWPAPSK="$3"
			uci set wireless.ap.ApCliAuthMode='WPAPSK'
			uci set wireless.ap.ApCliEncrypType='TKIP'
			uci set wireless.ap.ApCliEnable='1'
			;;
		WPA2PSK/TKIP )
			[ -n "$2" ] && uci set wireless.ap.ApCliSsid="$2"
			[ -n "$3" ] && uci set wireless.ap.ApCliWPAPSK="$3"
			uci set wireless.ap.ApCliAuthMode='WPA2PSK'
			uci set wireless.ap.ApCliEncrypType='TKIP'
			uci set wireless.ap.ApCliEnable='1'
			;;
		WPA2PSK/AES )
			[ -n "$2" ] && uci set wireless.ap.ApCliSsid="$2"
			[ -n "$3" ] && uci set wireless.ap.ApCliWPAPSK="$3"
			uci set wireless.ap.ApCliAuthMode='WPA2PSK'
			uci set wireless.ap.ApCliEncrypType='AES'
			uci set wireless.ap.ApCliEnable='1'
			;;
		WPA2PSK/TKIPAES )
			[ -n "$2" ] && uci set wireless.ap.ApCliSsid="$2"
			[ -n "$3" ] && uci set wireless.ap.ApCliWPAPSK="$3"
			uci set wireless.ap.ApCliAuthMode='WPA2PSK'
			uci set wireless.ap.ApCliEncrypType='AES'
			uci set wireless.ap.ApCliEnable='1'
			;;
		WPA1PSKWPA2PSK/TKIP)
			[ -n "$2" ] && uci set wireless.ap.ApCliSsid="$2"
			[ -n "$3" ] && uci set wireless.ap.ApCliWPAPSK="$3"
			uci set wireless.ap.ApCliAuthMode='WPA2PSK'
			uci set wireless.ap.ApCliEncrypType='TKIP'
			uci set wireless.ap.ApCliEnable='1'
			;;
		WPA1PSKWPA2PSK/AES)
			[ -n "$2" ] && uci set wireless.ap.ApCliSsid="$2"
			[ -n "$3" ] && uci set wireless.ap.ApCliWPAPSK="$3"
			uci set wireless.ap.ApCliAuthMode='WPA2PSK'
			uci set wireless.ap.ApCliEncrypType='AES'
			uci set wireless.ap.ApCliEnable='1'
			;;
		WPA1PSKWPA2PSK/TKIPAES)
			[ -n "$2" ] && uci set wireless.ap.ApCliSsid="$2"
			[ -n "$3" ] && uci set wireless.ap.ApCliWPAPSK="$3"
			uci set wireless.ap.ApCliAuthMode='WPA2PSK'
			uci set wireless.ap.ApCliEncrypType='AES'
			uci set wireless.ap.ApCliEnable='1'
			;;
	esac
	
	#搜索信道
	iwpriv apcli0 set SiteSurvey=1

	#等待一秒
	sleep 3


	#获取搜索结果
	CHANNEL=`iwpriv apcli0 get_site_survey | grep $2 | cut -d ' ' -f 1`
	#如果搜索出来的结果为空
	if [[ "$CHANNEL" == "" ]]; then
		uci set wireless.mt7628.channel=0
	#不为空
	else
		#把获取到的目标SSID的信道，赋值给网络配置文件
		uci set wireless.mt7628.channel=$CHANNEL

	fi

	#确认更改配置
	uci commit wireless
	uci set network.wan6.ifname='apcli0'
	uci set network.wan6.proto='dhcp'
	uci commit network
	sleep 1

	#重启网络
	/etc/init.d/network restart
else

echo "---------------------------------------------"
echo "       YDH iot Board Support list:"
echo "                NONE"
echo "                WPAPSK/AES"
echo "                WPAPSK/TKIP"
echo "                WPAPSK/TKIPAES"
echo "                WPA2PSK/AES"
echo "                WPA2PSK/TKIP"
echo "                WPA2PSK/TKIPAES"
echo "                WPA1PSKWPA2PSK/AES"
echo "                WPA1PSKWPA2PSK/TKIP"
echo "                WPA1PSKWPA2PSK/TKIPAES"
echo "---------------------------------------------"
fi

