#!/bin/sh
if [ -n "$1" ];then
	case $1 in
		search)
			iwpriv ra0 set SiteSurvey=1
			sleep 3
			iwpriv ra0 get_site_survey
			;;
		bridge)
			wifi down
			sleep 1
			if [ -n "$2" ];then
				uci set wireless.sta.ssid="$2"
				if [ -n "$3" ];then 
					uci set wireless.sta.key="$3"
				else
					uci delete wireless.sta.key
				fi
			fi
			uci delete network.wan
			uci delete network.wan6
			uci delete network.lan.ipaddr
			uci delete network.lan.netmask
			uci set dhcp.lan.ignore = 1
			uci set network.lan.ifname='apcli0 eth0.1 eth0.2'
			uci set network.lan.proto='dhcp'
			uci set wireless.sta.disabled=0
			uci commit
			/etc/init.d/network restart
			;;
		gateway)
			wifi down
			sleep 1
			if [ -n "$2" ];then
				uci set wireless.sta.ssid="$2"
				if [ -n "$3" ];then 
					uci set wireless.sta.key="$3"
				else
					uci delete wireless.sta.key
				fi
			fi
			uci delete network.wan
			uci delete network.wan6
			uci set network.lan.ifname='eth0.1'
			uci set network.lan.proto='static'
			uci set network.lan.ipaddr='192.168.10.1'
			uci set network.lan.netmask='255.255.255.0'
			uci set dhcp.lan.ignore = 0
			uci set network.wan='interface'
			uci set network.wan.proto='dhcp'
			uci set network.wan.ifname='apcli0'
			uci set wireless.sta.disabled=0
			uci commit
			/etc/init.d/network restart
			;;
		router)
			uci delete network.wan
			uci delete network.wan6
			uci set network.lan.ifname='eth0.1'
			uci set network.lan.proto='static'
			uci set network.lan.ipaddr='192.168.1.1'
			uci set network.lan.netmask='255.255.255.0'
			uci set dhcp.lan.ignore = 0
			uci set network.wan='interface'
			uci set network.wan.proto='dhcp'
			uci set network.wan.ifname='eth0.2'
			uci set network.wan6='interface'
			uci set network.wan6.proto='dhcpv6'
			uci set network.wan6.ifname='eth0.2'
			uci set wireless.sta.disabled=1
			uci commit
			/etc/init.d/network restart
			;;
	esac
else
echo "---------------------------------------------------"
echo "YDH Kit Staconfig help"
echo "MODE | search | bridge | gateway | router "
echo "\"staconfig search\""
echo "\"staconfig bridge ssid key\""
echo "\"staconfig gateway ssid key\""
echo "\"staconfig router\""
echo "---------------------------------------------------"
fi